; ////
; //////
; //////       J I A   S H E L L   E N V I R O N M E N T
; ////// ==============================
; //////
; ////// SILENTBYTE LICENSE NOTICE
; //////
; ////// THIS SOFTWARE IS PROVIDED BY THE AUTHOR 'AS IS' AND ANY EXPRESSED OR IMPLIED
; ////// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
; ////// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
; ////// EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
; ////// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
; ////// PROCUREMENT OF SUBSTITUTEGOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
; ////// BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
; ////// IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
; ////// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
; ////// POSSIBILITY OF SUCH DAMAGE.
; ////// 
; ////// THE CODE OF JIA FOUND IN THIS SOURCE FILE IS USING THE GPLv3 LICENSE.
; ////// FURTHER INFORMATION CAN BE FOUND IN THE ACCORDING LICENSE FILE.
; ////



EnableExplicit


; // region ...Constants...


#JIA_SUCCESS = 0
#JIA_FAILURE = 1


; // end region
; // region ...Procedures....


Procedure.i EntryPoint()
	
	If Not OpenConsole()
		ProcedureReturn #JIA_FAILURE
	EndIf
	
	
	CloseConsole()
	ProcedureReturn #JIA_SUCCESS
EndProcedure : End EntryPoint()


; // end region




; IDE Options = PureBasic 5.20 beta 7 (Windows - x86)
; CursorPosition = 43
; FirstLine = 18
; Folding = -
; EnableUnicode
; EnableXP